In [1]:
import pandas as pd

In [19]:
df = pd.read_excel(io='../data.xlsx').drop(df.columns[0], axis=1)

In [21]:
df.head()

,num,date,state,type,name,INN,owner,prew_owner,Last,Year,prev_lic,prev_date,forw_lic,forw_date,N,E
0,АБН00011НР,1993-06-08,Республика Хакасия,УВС,Новомихайловская площадь,1.904001e+09,АООТ Хакаснефтегазпром,NaN,True,1993,NaN,NaT,NaN,NaT,NaN,NaN
1,АБН00220НП,1997-10-07,Республика Хакасия,УВС,Ново-Михайловская площадь,2.466013e+09,ОАО Енисейнефтегаз,NaN,True,1997,NaN,NaT,NaN,NaT,"53°21'0.0839""N","91°40'0""Е"
2,АБН00385НП,2005-12-16,Республика Хакасия,УВС,Сохочульский участок,7.018007e+09,Федеральное государственное автономное учрежде...,NaN,False,2005,NaN,NaT,АБН00472НП,2007-12-05,"54°30'0.0828""N","89°49'59.88""Е"
3,АБН00472НП,2007-12-05,Республика Хакасия,УВС,Сохочульский участок,7.017109e+09,ООО Технологический инкубатор Томского политех...,Федеральное государственное автономное учрежде...,False,2007,АБН00385НП,2005-12-16,АБН00504НП,2009-06-24,"54°30'0.0828""N","89°49'59.9952""Е"
4,АБН00504НП,2009-06-24,Республика Хакасия,УВС,Сохочульский участок,7.017216e+09,ООО Сохочул,ООО Технологический инкубатор Томского политех...,True,2009,АБН00472НП,2005-12-16,NaN,NaT,"54°30'0.0828""N","89°49'59.9952""Е"

In [68]:
#Таблица владельцев лицензии - компания + ИНН
owners = df[['owner','INN']].drop_duplicates(keep='first')
owners['id'] = range(0, len(owners))

#присоединение столбца ID
df = pd.merge(df, owners[['owner', 'id']], on=['owner']).rename(columns={'id':'owner_id'}).drop(columns=['owner'])

In [40]:
place = df[['name']].drop_duplicates(keep='first')
place['id'] = range(0, len(place))

In [42]:
state = df['state'].drop_duplicates(keep='first')
state['id'] = range(0, len(state))

In [69]:
df

,num,date,state,type,name,INN,prew_owner,Last,Year,prev_lic,prev_date,forw_lic,forw_date,N,E,owner_id
0,АБН00011НР,1993-06-08,Республика Хакасия,УВС,Новомихайловская площадь,1.904001e+09,NaN,True,1993,NaN,NaT,NaN,NaT,NaN,NaN,0
1,АБН00220НП,1997-10-07,Республика Хакасия,УВС,Ново-Михайловская площадь,2.466013e+09,NaN,True,1997,NaN,NaT,NaN,NaT,"53°21'0.0839""N","91°40'0""Е",1
2,КРР00680НП,1998-04-07,Красноярский край,УВС,Аверинская 150,2.466013e+09,NaN,True,1998,NaN,NaT,NaN,NaT,"58°13'30.0784""N","91°52'30""Е",1
3,КРР00926НП,2000-04-17,Красноярский край,УВС,скв.Берямбинская 179,2.466013e+09,NaN,True,2000,NaN,NaT,NaN,NaT,"58°37'0.1978""N","99°48'0""Е",1
4,КРР01022НП,2000-10-06,Красноярский край,УВС,Иринчиминская 155,2.466013e+09,NaN,True,2000,NaN,NaT,NaN,NaT,"60°30'29.955""N","94°13'18.12""Е",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16998,ЯКУ15625НР,2013-11-01,Республика Саха (Якутия),УВС,Иктехский участок,3.849028e+09,ЗАО НафтаСиб-Иркутск,False,2013,ЯКУ15521НР,2013-03-25,ЯКУ15872НР,2015-04-16,"61°52'0.0728""N","113°58'10""Е",2943
16999,ЯКУ15815НР,2014-12-03,Республика Саха (Якутия),УВС,Мирнинский участок,1.435282e+09,"Открытое акционерное общество ""Якутская топлив...",False,2014,ЯКУ15095НР,2008-06-10,ЯКУ16436НР,2018-01-22,"62°35'0.0716""N","114°21'0""Е",2944
17000,ЯКУ15826НР,2014-12-17,Республика Саха (Якутия),УВС,NaN,1.435284e+09,"ООО ""Газодобывающая компания Ленск-газ""",False,2014,ЯКУ03916НР,2014-07-22,ЯКУ15886НР,2015-06-19,NaN,NaN,2945
17001,ЯКУ16004НР,2016-02-29,Республика Саха (Якутия),УВС,Карьер Мурбайский1; Карьер Мурбайский2; Карьер...,7.702388e+09,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""СЮЛЬ...",True,2016,ЯКУ04111НР,2015-02-13,NaN,NaT,"61°42'0.0731""N","114°53'0""Е",2946
17002,ЯКУ16436НР,2018-01-22,Республика Саха (Якутия),УВС,Мирнинский,1.435323e+09,"ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ ""МИРН...",True,2018,ЯКУ15815НР,2008-06-10,NaN,NaT,"62°35'0.0716""N","114°21'0""Е",2947

In [52]:
owners

                                                   owner           INN    id
0                                 АООТ Хакаснефтегазпром  1.904001e+09     0
1                                     ОАО Енисейнефтегаз  2.466013e+09     1
2      Федеральное государственное автономное учрежде...  7.018007e+09     2
3      ООО Технологический инкубатор Томского политех...  7.017109e+09     3
4                                            ООО Сохочул  7.017216e+09     4
...                                                  ...           ...   ...
16059  ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ЛЕНА...  3.849028e+09  2943
16065  ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МИРН...  1.435282e+09  2944
16066  ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КЭДЭ...  1.435284e+09  2945
16075  Общество с ограниченной ответственностью "Мурб...  7.702388e+09  2946
16086  ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "САХА...  1.435323e+09  2947

[2948 rows x 3 columns]

TypeError: unhashable type: 'Series'